---
- hosts: master
  
  tasks:
  - name: download k3s install script
    get_url:
      url: "https://get.k3s.io"
      dest: "/tmp/install_k3s.sh"
      mode: 755
    become: yes

  - name: install k3s server
    shell: "/tmp/install_k3s.sh"
    environment:
      INSTALL_K3S_EXEC: "server --advertise-address 172.16.0.1 --bind-address 172.16.0.1"
      INSTALL_K3S_VERSION: "v1.18.3+k3s1"
    become: yes

  - name: remove install script
    file:
      path: "/tmp/install_k3s.sh"
      state: absent
    become: yes

  - name: retrieve k3s token
    shell: cat /var/lib/rancher/k3s/server/node-token
    register: k3s_token
    become: yes

  - name: show k3s token
    debug:
      msg: "{{ k3s_token.stdout }}"
