name: minio image
on:
  push:
    branches:
    - master

jobs:
  build:
    name: build minio image action
    runs-on: ubuntu-18.04
    steps:
    - name: checkout source code
      uses: actions/checkout@master

    - name: check difference in minio code
      uses: technote-space/get-diff-action@v1.2.0
      id: code-diff
      with:
        PREFIX_FILTER: |
          image/minio
          .github/workflows/img-minio.yml
    
    - name: read image version
      uses: christian-draeger/read-properties@1.0.1
      id: image_version
      with:
        path: image/minio/image.properties
        property: version
      if: steps.code-diff.outputs.diff

    - name: set up docker buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.5
      id: buildx
      with:
        version: latest
      if: steps.code-diff.outputs.diff

    - name: login to docker hub
      run: |
        docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      if: steps.code-diff.outputs.diff

    - name: build
      run: |
        docker buildx build \
          --platform linux/arm64 \
          --output "type=image,name=docker.io/chiwanpark/minio:${{ steps.image_version.outputs.value }}-aarch64,push=true" \
          image/minio/
      if: steps.code-diff.outputs.diff
